# For more information: https://laravel.com/docs/sail
version: '3'
services:
  app:
    image: xwpd/php:7.4
    ports:
      - '${APP_PORT:-80}:80'
    working_dir: "/var/www/html"
    #entrypoint: ["php","artisan","serve","--host=0.0.0.0","--port=80"]
    volumes:
      - './docker/7.4/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro'
      - '.:/var/www/html'
      - './docker/7.4/php.ini:/usr/local/etc/php/php.ini'

  mysql:
    image: 'mysql:8.0'
    restart: always
    #ports:
    #    - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      #MYSQL_USER: 'root'
      #MYSQL_PASS: '123456'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'laravel'
    volumes:
      - './docker/mysql/data:/var/lib/mysql'

  redis:
    image: 'redis:alpine'
    restart: always
    #ports:
    #    - 6379:6379
    volumes:
      - './docker/redis/data:/data'

